import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button, XIcon, Input, ProgressBar, Container, Folder, Passcode } from '../components'
import { useState } from 'react'

export default function Home() {
  const [value, setValue] = useState('');

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button text="Hello world" />
      <Button icon={<XIcon />} />
      <Input onChange={e => setValue(e.target.value)} value={value} />
      <ProgressBar complete={30} total={60} />
      <Container title='test' hasMenu>
        Test
      </Container>
      <Folder />
      <Passcode code="1234" openFolder={() => {}} />
    </div>
  )
}
